Fcast MGparm averaging year value checks
nmfs-stock-synthesis/stock-synthesis pull request #472
Opened 2023-06-23 21:47 UTC by nschindler-noaa

## Concisely describe what has been changed/addressed in the pull request.

Fcast_MGparm_ave could have years set incorrectly. 

This accepts all year values and sets them according to the manual doc or at least to something that will not cause an error.

## What tests have been done? 
year value = -999, <0, <styr, >endyr

### Where are the relevant files?

 [x] No test files are required for this pull request. 

### What tests/review still need to be done?
I don't know of any.

## Is there an input change for users to Stock Synthesis? 

[x] No, there was no input change. 
This is an example of the input files (forecast.ss is the affected file).
[simple_averaging-copy.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11853263/simple_averaging-copy.zip)

## Additional information (optional).
This input:
 4 1 2001 1066
 3 0 10 -4
 5 1 2004 2500
 1 1 -999 -3
 2 1 1066 4
 8 0 3000 3000
produced this internal data:
 1 1 1971 1998
 2 1 1971 1972
 3 0 1971 1997
 4 1 2000 2001
 5 1 2000 2001
 0 0 0 0
 0 0 0 0
 8 0 2000 2001
and these messages in warning.sso
Warning 1 Adjustment: Fcast_MGparm_ave end year before start year, setting end year to: 1972
Warning 2 Adjustment: Fcast_MGparm_ave start year exceeds endyr, setting start year to: 2000
Warning 3 Adjustment: Fcast_MGparm_ave end year before start year, setting end year to: 2001
Warning 4 Adjustment: Fcast_MGparm_ave start year exceeds endyr, setting start year to: 2000
Warning 5 Adjustment: Fcast_MGparm_ave end year exceeds endyr, setting end year to: 2001
Warning 6 Adjustment: Fcast_MGparm_ave start year exceeds endyr, setting start year to: 2000
Warning 7 Adjustment: Fcast_MGparm_ave end year exceeds endyr, setting end year to: 2001

2023-06-23 21:59 UTC, Rick-Methot-NOAA requested changes
one change.  It should be OK to have minyr and maxyr both equal to endyr.  SO need to change logic here:
else if (Fcast_MGparm_ave_rd(i,3) >= endyr)

2023-06-24 00:58 UTC, nschindler-noaa commented
The results are now:
 1 1 1971 1998
 2 1 1971 1972
 3 0 1971 1997
 4 1 2001 2001
 5 1 2001 2001
 0 0 0 0
 0 0 0 0
 8 0 2001 2001
And the Warnings are not
Warning 1 Adjustment: Fcast_MGparm_ave maxyear before start year, setting to: 1972
Warning 2 Adjustment: Fcast_MGparm_ave maxyear before start year, setting to: 2002
Warning 3 Adjustment: Fcast_MGparm_ave maxyear exceeds endyr, setting to: 2001
Warning 4 Adjustment: Fcast_MGparm_ave minyear exceeds endyr, setting to: 2001
Warning 5 Adjustment: Fcast_MGparm_ave maxyear exceeds endyr, setting to: 2001
Warning 6 Adjustment: Fcast_MGparm_ave minyear exceeds endyr, setting to: 2001
Warning 7 Adjustment: Fcast_MGparm_ave maxyear exceeds endyr, setting to: 2001

2023-06-26 21:10 UTC, Rick-Methot-NOAA commented
I think it is OK, but the year values output in the warning do not match the year values in the results.

2023-06-26 22:57 UTC, Rick-Methot-NOAA commented
At lines ~4257:
no need for the +1 because OK for maxyear to be same as minyear.
Also, the warning statement should refer to minyear, not start year.

2023-06-26 23:00 UTC, nschindler-noaa commented
Thanks, Rick. I've made the changes, just doing a test run now.

2023-06-26 23:03 UTC, nschindler-noaa commented
The warnings are reduced to
Warning 1 Adjustment: Fcast_MGparm_ave maxyear before minyear, setting to: 1971
Warning 2 Adjustment: Fcast_MGparm_ave maxyear before minyear, setting to: 2001
Warning 3 Adjustment: Fcast_MGparm_ave minyear exceeds endyr, setting to: 2001
Warning 4 Adjustment: Fcast_MGparm_ave maxyear exceeds endyr, setting to: 2001
Warning 5 Adjustment: Fcast_MGparm_ave minyear exceeds endyr, setting to: 2001
Warning 6 Adjustment: Fcast_MGparm_ave maxyear exceeds endyr, setting to: 2001

2023-06-27 16:14 UTC, nschindler-noaa commented
I believe this is ready for merging.

2023-06-27 16:19 UTC, Rick-Methot-NOAA approved these changes
good to go

2023-06-27 16:20 UTC, merged