new fcast year approach
nmfs-stock-synthesis/stock-synthesis pull request #494
Opened 2023-08-15 03:50 UTC by Rick-Methot-NOAA

## Concisely describe what has been changed/addressed in the pull request.

* Resolves issue #493 

## What tests have been done? 
WIP, but basically working
### Where are the relevant files?

### What tests/review still need to be done?

- [ ] Need to check logic regarding fcast_specify_selex

## Is there an input change for users to Stock Synthesis? 

## Additional information (optional).

2023-08-15 16:23 UTC, e-gugliotti-NOAA commented
@Rick-Methot-NOAA - just made some changes to the workflows in PR #496 so that workflows won't be triggered if it is a draft PR. If you look at the bottom of the PR page, the only workflow triggered by the changes made was skipped because it is now a draft PR.

2023-08-18 19:52 UTC, Rick-Methot-NOAA commented
First test is nearly all passing.  Only the forecast catch for timevary growth and vermillion snapper are showing a small delta that cause failure.  I'll do a deep dive on that next.

2023-08-23 16:10 UTC, iantaylor-NOAA commented
I'm happy to review this but won't be able to get it done until after Sept 4 (I'm in FIMS meeting this week and have a manuscript review due, then going on leave Friday and next week).

2023-08-23 16:36 UTC, Rick-Methot-NOAA commented
Let's see if Brian can help out if Chantel cannot get to this either.
@chantelwetzel-noaa

2023-08-23 17:53 UTC, chantelwetzel-noaa requested changes
I have only suggested minor revisions here for clarity but it also appears that the model run actions are failing.  Is this still a draft pull request?  I looked around but did not see "draft" anywhere and based on the comments it looks like @e-gugliotti-NOAA fixed the actions for draft requests. Can someone confirm whether we would expect the model run actions to be passing or failing here?

2023-08-23 17:53 UTC, chantelwetzel-noaa commented on SS_write_ssnew.tpl
> +    NuFore << "#_Fcast_years for averaging:  beg_selex, end_selex, beg_relF, end_relF, beg_mean recruits, end_recruits  (enter actual year, or values of 0 or -integer to be rel. endyr)" << endl
In other places in the revised code, we use the word "mean" but here we use "average". I would suggest using one or the other for consistency.

2023-08-23 17:53 UTC, chantelwetzel-noaa commented on SS_write_ssnew.tpl
> +  NuFore << Fcast_Loop_Control(3) << " # Forecast base recruitment:  0= spawn_recr; 1=mult*spawn_recr_fxn; 2=mult*VirginRecr; 3=deprecated; 4=mult*average_over_yr_range" << endl;
"average_over_yr_range" revise to "mean_over_yr_range"

2023-08-23 17:53 UTC, chantelwetzel-noaa commented on SS_write_ssnew.tpl
> +  NuFore << "# for option 4, set phase for fore_recr_devs to -1 in control to get constant mean in MCMC, else devs will be applied" << endl;
I would revise for clarity "for forecast base recruitment option 4 (mult*mean_over_yr_range),"

2023-08-23 18:01 UTC, Rick-Methot-NOAA commented
The failing runs are all due to time-varying growth and in vermillion snapper.  I think this is not due to these new changes and I'll investigate.

2023-08-25 17:32 UTC, Rick-Methot-NOAA commented
something about the new code's handling of vermillion test case is still off.  Working on it.

2023-08-25 20:10 UTC, chantelwetzel-noaa approved these changes
These additional revisions look good to me and it is great we are now successfully passing all the checks.

2023-08-25 20:25 UTC, merged